name: Deploy Wiki

on:
  push:
    paths:
      - '.wiki/**'
    branches:
      - main

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        WIKI_DIR: .wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ github.event.pull_request.user.login }}@users.noreply.github.com
        GH_NAME: ${{ github.event.pull_request.user.login }}
